[background]
mode = "file"
path = "/home/jellybean/@nixos/nix/users/jellybean/veila/resources/background.png"
blur_strength = 0
dim_strength = 64

[lock]
acquire_timeout_seconds = 5
auto_reload_config = false
log_to_file = true
log_file_path = "~/.mix-logs/veila/config.log"
auth_backoff_base_ms = 512
auth_backoff_max_seconds = 12
hide_cursor = true
allow_empty_password = false
screen_off_seconds = 10
power_off_secondary_outputs = false
suspend_seconds = 256
suspend_only_on_battery = true
skip_suspend_while_media_playing = true

[visuals.avatar]
enabled = true
image_path = "/home/jellybean/@nixos/nix/users/jellybean/avatar.jpg"
size = 160
radius = 0
background_color = "#313244"
placeholder_padding = 20
ring_color = "#b4befe"
ring_width = 2
icon_color = "#FFFFFF"
halign = "center"
valign = "bottom"
x = 0
y = -120

[visuals.username]
enabled = true
text = "@libreaires"
font_family = "JetBrainsMono Nerd Font"
font_weight = 300
font_style = "normal"
color = "#b4befe"
font_size = 20
halign = "center"
valign = "bottom"
x = 0
y = -80

[visuals.input]
placeholder = "* There's a man behind the tree..."
reveal_on_interaction = true
reveal_mode = "input"
font_family = "JetBrainsMono Nerd Font"
font_weight = 400
font_style = "normal"
font_size = 16
background_color = "#313244"
border_color = "#6c7086"
width = 512
height = 32
radius = 0
border_width = 2
mask_color = "#FFFFFF"
halign = "center"
valign = "bottom"
x = 0
y = -20

[visuals.clock]
enabled = true
style = "standard"
format = "24h"
font_family = "JetBrainsMono Nerd Font"
font_weight = 600
font_style = "normal"
color = "#b4befe"
font_size = 80
meridiem_font_size = 20
meridiem_x = 6
meridiem_y = 8
halign = "center"
valign = "top"
x = 0
y = 40